# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://chizuchizu.com/"
DefaultContentLanguage  = "ja"
title                   = "I'm chizuchizu"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = "chizu-blog-hugo"
googleAnalytics         = "UA-130443536-1"
pluralizeListTitles     = false
disableLanguages        = ["en"]


[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "solarized-dark"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter","facebook","line","email"]

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "I'm chizuchizu"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "チズチズ(chizuchizu)"
    paragraph             = "14yo 統計学/Kaggle/Python/Linux"
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/icon.png"
      shape               = "circle"
      width               = ""
      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    about               = "チズチズという人が書いているブログです。気ままに技術系だったりまったり系の記事を投稿します。"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.ja]
    LanguageCode        = "ja"
    LanguageName        = "日本語"
    weight              = 9

[social]
  # Coding Communities
  github                = "chizuchizu"
#  stackoverflow         = "" # User Number

 # behance               = ""
 # dribbble              = ""
  # Publishing Communities
  # Professional/Business Oriented Communities
 # foursquare            = ""
 # xing                  = ""
 # slideshare            = ""
  # Social Networks
  #reddit                = "example"
  #quora                 = ""
  youtube               = "channel/UCUgUfVoiunYg48F7D3NRiRg"
  instagram             = "chizuchizu6"
  twitter               = "chizu_potato"

  #mastodon              = "example.com/@example"
  # Email
  email                 = "ochimasumi@gmail.com"
  atcoder               = "chizuchizu"
  kaggle                = "chizuchizu"
